///scr_init_hitloc_names()

ds_list_add(hitloc_names_inverse, "head");
ds_list_add(hitloc_names_inverse, "neck");
ds_list_add(hitloc_names_inverse, "torso_upper");
ds_list_add(hitloc_names_inverse, "torso_lower");
ds_list_add(hitloc_names_inverse, "left_arm_upper");
ds_list_add(hitloc_names_inverse, "left_arm_lower");
ds_list_add(hitloc_names_inverse, "left_hand");
ds_list_add(hitloc_names_inverse, "right_arm_upper");
ds_list_add(hitloc_names_inverse, "right_arm_lower");
ds_list_add(hitloc_names_inverse, "right_hand");
ds_list_add(hitloc_names_inverse, "left_leg_upper");
ds_list_add(hitloc_names_inverse, "left_leg_lower");
ds_list_add(hitloc_names_inverse, "left_foot");
ds_list_add(hitloc_names_inverse, "right_leg_upper");
ds_list_add(hitloc_names_inverse, "right_leg_lower");
ds_list_add(hitloc_names_inverse, "right_foot");
ds_list_add(hitloc_names_inverse, "none");
var i = 0;
ds_map_add(hitloc_names, "head", i++);
ds_map_add(hitloc_names, "neck", i++);
ds_map_add(hitloc_names, "torso_upper", i++);
ds_map_add(hitloc_names, "torso_lower", i++);
ds_map_add(hitloc_names, "left_arm_upper", i++);
ds_map_add(hitloc_names, "left_arm_lower", i++);
ds_map_add(hitloc_names, "left_hand", i++);
ds_map_add(hitloc_names, "right_arm_upper", i++);
ds_map_add(hitloc_names, "right_arm_lower", i++);
ds_map_add(hitloc_names, "right_hand", i++);
ds_map_add(hitloc_names, "left_leg_upper", i++);
ds_map_add(hitloc_names, "left_leg_lower", i++);
ds_map_add(hitloc_names, "left_foot", i++);
ds_map_add(hitloc_names, "right_leg_upper", i++);
ds_map_add(hitloc_names, "right_leg_lower", i++);
ds_map_add(hitloc_names, "right_foot", i++);
ds_map_add(hitloc_names, "none", i++);
